### ISSUE TITLE
Errors in smooth_data

### ISSUE THREAD

**Issue by cimentadaj** [timriffe/ODAPbackend#29]
Hi @TTRustam,

Check out the error I'm encountering below. Is this expected?
```r
res <-
  readr::read_csv("~/Downloads/abridged_data.csv") %>%
  ODAPbackend:::create_groupid(c("Sex", "Province"))

smooth_result <- smooth_flexible(
    res,
    variable = "Deaths",
    rough_method = "United Nations",
    fine_method = "none",
    constrain_infants = TRUE,
    age_out = "abridged"
  )
Error in `map()` at ODAPbackend/R/graduation.R:74:3:
ℹ In index: 1.
Caused by error in `splinefun()`:
! 'y' must be increasing or decreasing
Run `rlang::last_trace()` to see where the error occurred.
```

Note that I created some fake data so I made up numbers. The point I want to make sure is simply whether this can happen to a real user with real data, because if it is, then we should handle this in the `check_data`. I think all user interactions with the app should never fail so we should never have to worry about some function not working.

Attaching the data I used: [abridged_data.csv](https://github.com/user-attachments/files/17355265/abridged_data.csv)

**Comment by TTRustam** [comment]
Somewhat fixed. The problem lies with the data and DemoTools method. I have added a corresponding check to the function. If the data turn negative most likely it is the problem with the data, not the method. In this case, the user is suggested to use another method. This problem only occurs with the UN method.
Corresponding error and message added.
