### ISSUE TITLE
lt_flexible not accepting single ages

### ISSUE THREAD

**Issue by cimentadaj** [timriffe/ODAPbackend#34]
@timriffe @TTRustam I was under the impression that I could start with 5 year age groups, smooth them to single ages and pass that to lt_flexible. Here's the [single_ages_error.csv](https://github.com/user-attachments/files/17509066/single_ages_error.csv) and the code:

```r
read_csv("~/Downloads/single_ages_error.csv") %>%
  lt_flexible(
    OAnew = 100,
    age_out = "single",
    extrapFrom = 80,
    extrapFit = seq(60, 100, by = 5),
    extrapLaw = "Kannisto",
    radix = 100000,
    SRB = 1.05,
    a0rule = "Andreev-Kingkade",
    axmethod = "UN (Greville)",
    Sex = "Total"
  )
```
```
Rows: 404 Columns: 9
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (3): .id_label, Sex, Province
dbl (6): .id, Exposures, Age, Deaths, Rates, AgeInt

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error in `reframe()` at ODAPbackend/R/lifetables.R:88:3:
ℹ In argument: `lt_flexible_chunk(...)`.
ℹ In group 1: `.id = 4`.
Caused by error in `lt_abridged2single()` at ODAPbackend/R/lifetables.R:224:5:
! is_abridged(Age) is not TRUE
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by TTRustam** [comment]
Good afternoon Jorge.

Regarding this problem, the answer is yes, you can!
The problem is as follows:
1) Due to the function design it is better to use something like:
data <- read_csv("~/Downloads/single_ages_error.csv")
lt_flexible(
data,
    OAnew = 100,
    age_out = "single",
    extrapFrom = 80,
    extrapFit = seq(60, 100, by = 5),
    extrapLaw = "Kannisto",
    radix = 100000,
    SRB = 1.05,
    a0rule = "Andreev-Kingkade",
    axmethod = "UN (Greville)",
    Sex = "Total"
  )
*rather than piping %>% the data to function.*
2) The error you are encountering is because of this line 38: by_args <-
names(data_in)[!names(data_in) %in% c("Age", "Deaths", "Exposures",
"Mx_emp")]
See, your data has more columns than I have suspected, namely it also has
"Rates",  and "AgeInt" columns. Currently, the function tries to use them
as groups and breaks. If you replace the code at line 38 in the
lifetables file with   by_args <- names(data_in)[!names(data_in) %in%
c("Age", "Deaths", "Exposures", "Mx_emp", "Rates", "AgeInt")], everything
will work.
I think we should decide on what columns we expect to show up in the data,
thank you very much for noticing this Jorge.

Best regards,
Rustam.

чт, 24 окт. 2024 г. в 17:13, Jorge Cimentada ***@***.***>:

**Comment by TTRustam** [comment]
fixed
